### ISSUE TITLE
Adding GFF instead of GFF3 crashes BasePlayer

### ISSUE THREAD

**Issue by esaskar** [rkataine/BasePlayer#3]
Trace:
```
java.lang.NullPointerException at base.BasePlayer.FileRead.readGFF(FileRead.java:4500)
at base.BasePlayer.AddGenome.parseGFF(AddGenome.java:251)
at base.BasePlayer.AddGenome$OutputRunner.createGenome(AddGenome.java:186)
at base.BasePlayer.AddGenome$OutputRunner.doInBackground(AddGenome.java:99)
at base.BasePlayer.AddGenome$OutputRunner.doInBackground(AddGenome.java:1)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by rkataine** [comment]
only gff3 can be added as an annotation file
